/*	$NetBSD$	*/

/*
 * Copyright (c) 2018 Ryo Shimizu <ryo@nerv.org>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Qualcomm Snapdragon family SoC UART/UART_DM
 */

#ifndef _MSM_UARTREG_H_
#define _MSM_UARTREG_H_

#include <sys/param.h>
#include <sys/types.h>

/* UART */
#define UART_MR1			0x00000000	/* read/write */
#define  UART_MR1_AUTO_RFR_LEVEL1	__BITS(10,8)
#define  UART_MR1_RX_RDY_CTL		__BIT(7)
#define  UART_MR1_CTS_CTL		__BIT(6)
#define  UART_MR1_AUTO_RFR_LEVEL0	__BITS(5,0)
#define UART_MR2			0x00000004	/* read/write */
#define  UART_MR2_ERROR_MODE		__BIT(6)
#define  UART_MR2_BITS_PER_CHAR		__BITS(5,4)
#define  UART_MR2_5BITS_PER_CHAR	__SHIFTIN(0, UART_MR2_BITS_PER_CHAR)
#define  UART_MR2_6BITS_PER_CHAR	__SHIFTIN(1, UART_MR2_BITS_PER_CHAR)
#define  UART_MR2_7BITS_PER_CHAR	__SHIFTIN(2, UART_MR2_BITS_PER_CHAR)
#define  UART_MR2_8BITS_PER_CHAR	__SHIFTIN(3, UART_MR2_BITS_PER_CHAR)
#define  UART_MR2_STOP_BIT_LEN		__BITS(3,2)
#define  UART_MR2_PARITY_MODE		__BITS(1,0)
#define  UART_MR2_PARITY_NONE		__SHIFTIN(0, UART_MR2_PARITY_MODE)
#define  UART_MR2_PARITY_ODD		__SHIFTIN(1, UART_MR2_PARITY_MODE)
#define  UART_MR2_PARITY_EVEN		__SHIFTIN(2, UART_MR2_PARITY_MODE)
#define  UART_MR2_PARITY_SPACE		__SHIFTIN(3, UART_MR2_PARITY_MODE)
#define UART_CSR			0x00000008	/* write */
#define  UART_CSR_UART_RX_CLK_SEL	__BITS(7,4)
#define  UART_CSR_UART_TX_CLK_SEL	__BITS(3,0)
#define UART_SR				0x00000008	/* read */
#define  UART_SR_HUNT_CHAR		__BIT(7)
#define  UART_SR_RX_BREAK		__BIT(6)
#define  UART_SR_PAR_FRAME_ERR		__BIT(5)
#define  UART_SR_UART_OVERRUN		__BIT(4)
#define  UART_SR_TXEMT			__BIT(3)
#define  UART_SR_TXRDY			__BIT(2)
#define  UART_SR_RXFULL			__BIT(1)
#define  UART_SR_RXRDY			__BIT(0)
#define UART_TF				0x0000000c	/* write */
#define UART_RF				0x0000000c	/* read */
#define UART_CR				0x00000010	/* write */
#define  UART_CR_CH_CMD			__BITS(7,4)
#define  UART_CR_CH_CMD_NULL		__SHIFTIN(0, UART_CR_CMD)
#define  UART_CR_CH_CMD_RST_RX		__SHIFTIN(1, UART_CR_CMD)
#define  UART_CR_CH_CMD_RST_TX		__SHIFTIN(2, UART_CR_CMD)
#define  UART_CR_CH_CMD_RST_ERRSTAT	__SHIFTIN(3, UART_CR_CMD)
#define  UART_CR_CH_CMD_RST_BRK_CHG_INT	__SHIFTIN(4, UART_CR_CMD)
#define  UART_CR_CH_CMD_START_BRK	__SHIFTIN(5, UART_CR_CMD)
#define  UART_CR_CH_CMD_STOP_BRK	__SHIFTIN(6, UART_CR_CMD)
#define  UART_CR_CH_CMD_RST_CTS_N	__SHIFTIN(7, UART_CR_CMD)
#define  UART_CR_CH_CMD_PACKET_MODE	__SHIFTIN(9, UART_CR_CMD)
#define  UART_CR_CH_CMD_MODE_RESET	__SHIFTIN(12, UART_CR_CMD)
#define  UART_CR_CH_CMD_SET_RFR_N	__SHIFTIN(13, UART_CR_CMD)
#define  UART_CR_CH_CMD_RST_RFR_N	__SHIFTIN(14, UART_CR_CMD)
#define  UART_CR_CH_CMD_UNDEF		__SHIFTIN(15, UART_CR_CMD)
#define  UART_CR_UART_TX_DIS		__BIT(3)
#define  UART_CR_UART_TX_EN		__BIT(2)
#define  UART_CR_UART_RX_DIS		__BIT(1)
#define  UART_CR_UART_RX_EN		__BIT(0)
#define UART_MISR			0x00000010	/* read */
#define UART_IMR			0x00000014	/* write */
#define UART_ISR			0x00000014	/* read */
#define  UART_IRQBIT_CURRENT_CTS	__BIT(6)
#define  UART_IRQBIT_DELTA_CTS		__BIT(5)
#define  UART_IRQBIT_RXLEV		__BIT(4)
#define  UART_IRQBIT_RXSTALE		__BIT(3)
#define  UART_IRQBIT_RXBREAK		__BIT(2)
#define  UART_IRQBIT_RXHUNT		__BIT(1)
#define  UART_IRQBIT_TXLEV		__BIT(0)
#define UART_IPR			0x00000018	/* read/write */
#define  UART_IPR_STALE_TIMEOUT_MSB	__BITS(10,7)
#define  UART_IPR_SAMPLE_DATA		__BIT(6)
#define  UART_IPR_RXSTALE_LAST		__BIT(5)
#define  UART_IPR_STALE_TIMEOUT_LSB	__BITS(4,0)
#define UART_TFWR			0x0000001c	/* read/write */
#define UART_RFWR			0x00000020	/* read/write */
#define UART_HCR			0x00000024	/* read/write */
#define UART_MREG			0x00000028	/* read/write */
#define UART_NREG			0x0000002c	/* read/write */
#define UART_DREG			0x00000030	/* read/write */
#define UART_MNDREG			0x00000034	/* read/write */
#define  UART_MNDREG_MREG_LSB		__BIT(5)
#define  UART_MNDREG_NREG_LSB		__BITS(4,2)
#define  UART_MNDREG_DREG_LSB		__BITS(1,0)
#define UART_IRDA			0x00000038	/* read/write */
#define  UART_IRDA_INVERT_IRDA_TX	__BIT(2)
#define  UART_IRDA_INVERT_IRDA_RX	__BIT(1)
#define  UART_IRDA_IRDA_EN		__BIT(0)

/* UART_DM */
#define UART_DM_MR1			0x00000000
#define  UART_DM_MR1_AUTO_RFR_LEVEL1	__BITS(31,8)
#define  UART_DM_MR1_RX_RDY_CTL		__BIT(7)
#define  UART_DM_MR1_RX_RDY_CTL		__BIT(7)
#define  UART_DM_MR1_CTS_CTL		__BIT(6)
#define  UART_DM_MR1_AUTO_RFR_LEVEL0	__BITS(5,0)
#define UART_DM_MR2			0x00000004
#define  UART_DM_MR2_RFR_CTS_LOOPBACK	__BIT(10)
#define  UART_DM_MR2_RX_ERROR_CHAR_OFF	__BIT(9)
#define  UART_DM_MR2_RX_BREAK_ZERO_CHAR_OFF __BIT(8)
#define  UART_DM_MR2_LOOPBACK		__BIT(7)
#define  UART_DM_MR2_ERROR_MODE		__BIT(6)
#define  UART_DM_MR2_BITS_PER_CHAR	__BITS(5,4)
#define  UART_DM_MR2_5BITS_PER_CHAR	__SHIFTIN(0, UART_DM_MR2_BITS_PER_CHAR)
#define  UART_DM_MR2_6BITS_PER_CHAR	__SHIFTIN(1, UART_DM_MR2_BITS_PER_CHAR)
#define  UART_DM_MR2_7BITS_PER_CHAR	__SHIFTIN(2, UART_DM_MR2_BITS_PER_CHAR)
#define  UART_DM_MR2_8BITS_PER_CHAR	__SHIFTIN(3, UART_DM_MR2_BITS_PER_CHAR)
#define  UART_DM_MR2_STOP_BIT_LEN	__BITS(3,2)
#define  UART_DM_MR2_PARITY_MODE	__BITS(1,0)
#define  UART_DM_MR2_PARITY_NONE	__SHIFTIN(0, UART_DM_MR2_PARITY_MODE)
#define  UART_DM_MR2_PARITY_ODD		__SHIFTIN(1, UART_DM_MR2_PARITY_MODE)
#define  UART_DM_MR2_PARITY_EVEN	__SHIFTIN(2, UART_DM_MR2_PARITY_MODE)
#define  UART_DM_MR2_PARITY_SPACE	__SHIFTIN(3, UART_DM_MR2_PARITY_MODE)
#define UART_DM_XXX_CSR_SR		0x00000008	/* deprecated */
#define UART_DM_XXX_CR_MISR		0x00000010	/* deprecated */
#define UART_DM_XXX_IMR_ISR		0x00000014	/* deprecated */
#define UART_DM_IPR			0x00000018
#define  UART_DM_IPR_STALE_TIMEOUT_MSB	__BITS(31,7)
#define  UART_DM_IPR_SAMPLE_DATA	__BIT(6)
#define  UART_DM_IPR_STALE_TIMEOUT_LSB	__BITS(4,0)
#define UART_DM_TFWR			0x0000001c
#define UART_DM_RFWR			0x00000020
#define UART_DM_HCR			0x00000024
#define UART_DM_DMRX			0x00000034
#define UART_DM_XXX_IRDA_RX_TOTAL_SNAP	0x00000038	/* deprecated */
#define UART_DM_DMEN			0x0000003c
#define  UART_DM_DMEN_RX_SC_EN		__BIT(5)
#define  UART_DM_DMEN_TX_SC_EN		__BIT(4)
#define  UART_DM_DMEN_RX_BAM_EN		__BIT(3)
#define  UART_DM_DMEN_TX_BAM_EN		__BIT(2)
#define UART_DM_NO_CHARS_FOR_TX		0x00000040
#define UART_DM_BADR			0x00000044
#define UART_DM_TXFS			0x0000004c
#define  UART_DM_TXFS_TX_FIFO_STATE_MSB	__BITS(31,14)
#define  UART_DM_TXFS_TX_ASYNC_FIFO_STATE __BITS(13,10)
#define  UART_DM_TXFS_TX_BUFFER_STATE	__BITS(9,7)
#define  UART_DM_TXFS_TX_FIFO_STATE_LSB	__BITS(6,0)
#define UART_DM_RXFS			0x00000050
#define  UART_DM_RXFS_RX_FIFO_STATE_MSB	__BITS(31,14)
#define  UART_DM_RXFS_RX_ASYNC_FIFO_STATE __BITS(13,10)
#define  UART_DM_RXFS_RX_BUFFER_STATE	__BITS(9,7)
#define  UART_DM_RXFS_RX_FIFO_STATE_LSB	__BITS(6,0)
#define UART_DM_MISR_MODE		0x00000060
#define  UART_DM_MISR_MODE_MODE		__BITS(1,0)
#define UART_DM_MISR_RESET		0x00000064
#define  UART_DM_MISR_RESET_RESET	__BIT(0)
#define UART_DM_MISR_EXPORT		0x00000068
#define  UART_DM_MISR_EXPORT_EXPORT	__BIT(0)
#define UART_DM_MISR_VAL		0x0000006c
#define UART_DM_XXX_TF_RF		0x00000070	/* deprecated */
#define UART_DM_XXX_TF_RF_2		0x00000074	/* deprecated */
#define UART_DM_XXX_TF_RF_3		0x00000078	/* deprecated */
#define UART_DM_XXX_TF_RF_4		0x0000007c	/* deprecated */
#define UART_DM_SIM_CFG			0x00000080
#define  UART_DM_SIM_CFG_UIM_TX_MODE	__BIT(17)
#define  UART_DM_SIM_CFG_UIM_RX_MODE	__BIT(16)
#define  UART_DM_SIM_CFG_SIM_STOP_BIT_LEN __BITS(15,8)
#define  UART_DM_SIM_CFG_SIM_CLK_ON	__BIT(7)
#define  UART_DM_SIM_CFG_SIM_CLK_TD8_SEL __BIT(6)
#define  UART_DM_SIM_CFG_SIM_CLK_STOP_HIGH __BIT(5)
#define  UART_DM_SIM_CFG_MASK_RX	__BIT(3)
#define  UART_DM_SIM_CFG_SWAP_D		__BIT(2)
#define  UART_DM_SIM_CFG_INV_D		__BIT(1)
#define  UART_DM_SIM_CFG_SIM_SEL	__BIT(0)
#define UART_DM_CSR			0x000000a0
#define  UART_DM_CSR_UART_RX_CLK_SEL	__BITS(7,4)
#define  UART_DM_CSR_UART_TX_CLK_SEL	__BITS(3,0)
#define UART_DM_SR			0x000000a4
#define  UART_DM_SR_TRANS_END_TRIGGER	__BITS(11,10)
#define  UART_DM_SR_TRANS_ACTIVE	__BIT(9)
#define  UART_DM_SR_RX_BREAK_START_LAST	__BIT(8)
#define  UART_DM_SR_HUNT_CHAR		__BIT(7)
#define  UART_DM_SR_RX_BREAK		__BIT(6)
#define  UART_DM_SR_PAR_FRAME_ERR	__BIT(5)
#define  UART_DM_SR_UART_OVERRUN	__BIT(4)
#define  UART_DM_SR_TXEMT		__BIT(3)
#define  UART_DM_SR_TXRDY		__BIT(2)
#define  UART_DM_SR_RXFULL		__BIT(1)
#define  UART_DM_SR_RXRDY		__BIT(0)
#define UART_DM_CR			0x000000a8
#define  UART_DM_CR_CH_CMD_MSB		__BIT(11)
#define  UART_DM_CR_GEN_CMD		__BITS(10,8)
#define  UART_DM_CR_GEN_CMD_NULL	__SHIFTIN(0, UART_DM_CR_GEN_CMD)
#define  UART_DM_CR_GEN_CMD_EN_CR_PROT	__SHIFTIN(1, UART_DM_CR_GEN_CMD)
#define  UART_DM_CR_GEN_CMD_DIS_CR_PROT	__SHIFTIN(2, UART_DM_CR_GEN_CMD)
#define  UART_DM_CR_GEN_CMD_RST_TX_RDY	__SHIFTIN(3, UART_DM_CR_GEN_CMD)
#define  UART_DM_CR_GEN_CMD_FRC_STALE	__SHIFTIN(4, UART_DM_CR_GEN_CMD)
#define  UART_DM_CR_GEN_CMD_EN_STALE	__SHIFTIN(5, UART_DM_CR_GEN_CMD)
#define  UART_DM_CR_GEN_CMD_DIS_STALE	__SHIFTIN(6, UART_DM_CR_GEN_CMD)
#define  UART_DM_CR_CH_CMD_LSB		__BITS(7,4)
#define  UART_DM_CR_UART_TX_DIS		__BIT(3)
#define  UART_DM_CR_UART_TX_EN		__BIT(2)
#define  UART_DM_CR_UART_RX_DIS		__BIT(1)
#define  UART_DM_CR_UART_RX_EN		__BIT(0)
#define UART_DM_MISR			0x000000ac
#define UART_DM_IMR			0x000000b0
#define UART_DM_ISR			0x000000b4
#define  UART_DM_IRQBIT_WWT_IRQ		__BIT(16)
#define  UART_DM_IRQBIT_TXCOMP_IRQ	__BIT(15)
#define  UART_DM_IRQBIT_RX_RD_ERROR_IRQ	__BIT(14)
#define  UART_DM_IRQBIT_TX_WR_ERROR_IRQ	__BIT(13)
#define  UART_DM_IRQBIT_PAR_FRAME_ERR_IRQ __BIT(12)
#define  UART_DM_IRQBIT_RXBREAK_END	__BIT(11)
#define  UART_DM_IRQBIT_RXBREAK_START	__BIT(10)
#define  UART_DM_IRQBIT_TX_DONE		__BIT(9)
#define  UART_DM_IRQBIT_TX_ERROR	__BIT(8)
#define  UART_DM_IRQBIT_TX_READY	__BIT(7)
#define  UART_DM_IRQBIT_CURRENT_CTS	__BIT(6)
#define  UART_DM_IRQBIT_DELTA_CTS	__BIT(5)
#define  UART_DM_IRQBIT_RXLEV		__BIT(4)
#define  UART_DM_IRQBIT_RXSTALE		__BIT(3)
#define  UART_DM_IRQBIT_RXBREAK_CHANGE	__BIT(2)
#define  UART_DM_IRQBIT_RXHUNT		__BIT(1)
#define  UART_DM_IRQBIT_TXLEV		__BIT(0)
#define UART_DM_IRDA			0x000000b8
#define  UART_DM_IRDA_RATE_EN		__BIT(4)
#define  UART_DM_IRDA_IRDA_LOOPBACK	__BIT(3)
#define  UART_DM_IRDA_INVERT_IRDA_TX	__BIT(2)
#define  UART_DM_IRDA_INVERT_IRDA_RX	__BIT(1)
#define  UART_DM_IRDA_IRDA_EN		__BIT(0)
#define UART_DM_RX_TOTAL_SNAP		0x000000bc
#define UART_DM_WWT_TIMEOUT		0x000000c0
#define UART_DM_CLK_CTRL		0x000000c4
#define  UART_DM_CLK_CTRL_UART_IRDA_CLK_CGC_OPEN	__BIT(23)
#define  UART_DM_CLK_CTRL_UART_SIM_CLK_CGC_OPEN		__BIT(22)
#define  UART_DM_CLK_CTRL_UART_RX_CLK_CGC_OPEN		__BIT(21)
#define  UART_DM_CLK_CTRL_UART_TX_CLK_CGC_OPEN		__BIT(20)
#define  UART_DM_CLK_CTRL_AHB_RX_BAM_CLK_CGC_OPEN	__BIT(14)
#define  UART_DM_CLK_CTRL_AHB_TX_BAM_CLK_CGC_OPEN	__BIT(13)
#define  UART_DM_CLK_CTRL_AHB_RX_CLK_CGC_OPEN		__BIT(10)
#define  UART_DM_CLK_CTRL_AHB_TX_CLK_CGC_OPEN		__BIT(9)
#define  UART_DM_CLK_CTRL_AHB_WR_CLK_CGC_OPEN		__BIT(8)
#define  UART_DM_CLK_CTRL_RX_ENABLE_CGC_OPT		__BIT(5)
#define  UART_DM_CLK_CTRL_TX_ENABLE_CGC_OPT		__BIT(4)
#define  UART_DM_CLK_CTRL_AHB_CLK_CGC_CLOSE		__BIT(0)
#define UART_DM_BCR			0x000000c8
#define  UART_DM_BCR_RX_DMRX_1BYTE_RES_EN	__BIT(5)
#define  UART_DM_BCR_RX_STALE_IRQ_DMRX_EQUAL	__BIT(4)
#define  UART_DM_BCR_RX_DMRX_LOW_EN		__BIT(2)
#define  UART_DM_BCR_STALE_IRQ_EMPTY		__BIT(1)
#define  UART_DM_BCR_TX_BREAK_DISABLE		__BIT(0)
#define UART_DM_RX_TRANS_CTRL		0x000000cc
#define  UART_DM_RX_TRANS_CTRL_RX_DMRX_CYCLIC_EN		__BIT(2)
#define  UART_DM_RX_TRANS_CTRL_RX_TRANS_AUTO_RE_ACTIVATE	__BIT(1)
#define  UART_DM_RX_TRANS_CTRL_RX_STALE_AUTO_RE_EN		__BIT(0)
#define UART_DM_FSM_STATUS		0x000000d4
#define  UART_DM_FSM_STATUS_TX_COMP_FSM			__BITS(29,28)
#define  UART_DM_FSM_STATUS_RX_PACK_FSM			__BITS(26,24)
#define  UART_DM_FSM_STATUS_RX_TRANS_FSM		__BITS(21,20)
#define  UART_DM_FSM_STATUS_TX_TRANS_FSM		__BITS(18,16)
#define  UART_DM_FSM_STATUS_RX_PRO_TRANS_END_FSM	__BITS(14,12)
#define  UART_DM_FSM_STATUS_RX_PRO_ACTIVE_FSM		__BITS(10,8)
#define  UART_DM_FSM_STATUS_TX_CON_TRANS_END_FSM	__BITS(6,4)
#define  UART_DM_FSM_STATUS_RX_TRANSFER_ACTIVE		__BIT(0)
#define UART_DM_GENERICS		0x000000dc
#define  UART_DM_GENERICS_GENERIC_BAM_IFC	__BIT(7)
#define  UART_DM_GENERICS_GENERIC_DM_IFC	__BIT(6)
#define  UART_DM_GENERICS_GENERIC_IRDA_IFC	__BIT(5)
#define  UART_DM_GENERICS_GENERIC_SIM_GLUE	__BIT(4)
#define  UART_DM_GENERICS_GENERIC_RAM_ADDR_WIDTH __BITS(3,0)
#define UART_DM_TF			0x00000100
#define UART_DM_TF_2			0x00000104
#define UART_DM_TF_3			0x00000108
#define UART_DM_TF_4			0x0000010c
#define UART_DM_TF_5			0x00000110
#define UART_DM_TF_6			0x00000114
#define UART_DM_TF_7			0x00000118
#define UART_DM_TF_8			0x0000011c
#define UART_DM_TF_9			0x00000120
#define UART_DM_TF_10			0x00000124
#define UART_DM_TF_11			0x00000128
#define UART_DM_TF_12			0x0000012c
#define UART_DM_TF_13			0x00000130
#define UART_DM_TF_14			0x00000134
#define UART_DM_TF_15			0x00000138
#define UART_DM_TF_16			0x0000013c
#define UART_DM_RF			0x00000140
#define UART_DM_RF_2			0x00000144
#define UART_DM_RF_3			0x00000148
#define UART_DM_RF_4			0x0000014c
#define UART_DM_RF_5			0x00000150
#define UART_DM_RF_6			0x00000154
#define UART_DM_RF_7			0x00000158
#define UART_DM_RF_8			0x0000015c
#define UART_DM_RF_9			0x00000160
#define UART_DM_RF_10			0x00000164
#define UART_DM_RF_11			0x00000168
#define UART_DM_RF_12			0x0000016c
#define UART_DM_RF_13			0x00000170
#define UART_DM_RF_14			0x00000174
#define UART_DM_RF_15			0x00000178
#define UART_DM_RF_16			0x0000017c
#define UART_DM_UIM_CFG			0x00000180
#define  UART_DM_UIM_CFG_BATT_ALARM_QUICK_DROP_EN	__BIT(15)
#define  UART_DM_UIM_CFG_TESTBUS_EN			__BIT(14)
#define  UART_DM_UIM_CFG_SW_RESET			__BIT(13)
#define  UART_DM_UIM_CFG_MODE18				__BIT(12)
#define  UART_DM_UIM_CFG_PMIC_ALARM_EN			__BIT(10)
#define  UART_DM_UIM_CFG_BATT_ALARM_TRIGGER_EN		__BIT(9)
#define  UART_DM_UIM_CFG_UIM_RMV_TRIGGER_EN		__BIT(8)
#define  UART_DM_UIM_CFG_UIM_CARD_EVENTS_ENABLE		__BIT(6)
#define  UART_DM_UIM_CFG_UIM_PRESENT_POLARITY		__BIT(5)
#define  UART_DM_UIM_CFG_EVENT_DEBOUNCE_TIME		__BITS(4,0)
#define UART_DM_UIM_CMD			0x00000184
#define  UART_DM_UIM_CMD_RECOVER_FROM_HW_DEACTIVATION	__BIT(1)
#define  UART_DM_UIM_CMD_INITIATE_HW_DEACTIVATION	__BIT(0)
#define UART_DM_UIM_IO_STATUS		0x00000188
#define  UART_DM_UIM_IO_STATUS_UIM_IO_WRITE_IN_PROGRESS	__BIT(2)
#define  UART_DM_UIM_IO_STATUS_UIM_DEACTIVATION_STATUS	__BIT(1)
#define  UART_DM_UIM_IO_STATUS_CARD_PRESENCE		__BIT(0)
#define UART_DM_UIM_IRQ_ISR		0x0000018c
#define UART_DM_UIM_IRQ_MISR		0x00000190
#define UART_DM_UIM_IRQ_CLR		0x00000194
#define UART_DM_UIM_IRQ_IMR		0x00000198
#define UART_DM_UIM_IRQ_IMR_SET		0x0000019c
#define UART_DM_UIM_IRQ_IMR_CLR		0x000001a0
#define  UART_DM_UIM_IRQBIT_UIM_IO_WRITE_DONE		__BIT(4)
#define  UART_DM_UIM_IRQBIT_HW_SEQUENCE_FINISH		__BIT(3)
#define  UART_DM_UIM_IRQBIT_BATT_ALARM			__BIT(2)
#define  UART_DM_UIM_IRQBIT_UIM_CARD_INSERTION		__BIT(1)
#define  UART_DM_UIM_IRQBIT_UIM_CARD_REMOVAL		__BIT(0)

#endif /* _MSM_UARTREG_H_ */
