# $NetBSD: Makefile,v 1.1 2014/08/10 05:47:37 matt Exp $

INCSDIR= /usr/include/aarch64

INCS=	ansi.h aout_machdep.h armreg.h asm.h \
	bswap.h byte_swap.h \
	cdefs.h cpu.h \
	disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	fenv.h frame.h \
	ieee.h ieeefp.h \
	int_mwgwtypes.h int_types.h \
	intr.h \
	kcore.h \
	lock.h \
	math.h mcontext.h \
	param.h pcb.h pmap.h \
	proc.h profile.h pte.h ptrace.h \
	reg.h \
	setjmp.h signal.h \
	types.h \
	vmparam.h

.include <bsd.kinc.mk>
